In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import pandas as pd
data={
    "Name":["Alice","Bob","Charlie"],
    "Age":[25,30,35],
    "City":["New York","San Francisco","Los Angeles"]
}

df=pd.DataFrame(data)
df.set_index('Name', inplace=True)
df.index = ['A', 'B', 'C']

In [23]:
df.reset_index(drop=True,inplace=True)
df.loc[0]

Age           25
City    New York
Name: 0, dtype: object

In [14]:
df.head()

   Age           City
A   25       New York
B   30  San Francisco
C   35    Los Angeles

In [15]:
data={1:"kartik",2:"gaurav",3:"hritik"}
df1=pd.Series(data)
df1.head()

1    kartik
2    gaurav
3    hritik
dtype: object

In [28]:
df=pd.read_csv("mustafa brand.csv")
df.head()

   date  month  year gender  total m  obtain m
0     1      1  2025   male      555       551
1     2      1  2025   male      555       550
2     3      1  2025   male      555       540
3     4      1  2025   male      555       534
4     5      1  2025   male      555       521

In [32]:
my_df=df.groupby('obtain m')['total m'].mean()/df['total m'].sum()
my_df

obtain m
341    0.033333
342    0.033333
343    0.033333
345    0.033333
365    0.033333
366    0.033333
377    0.033333
400    0.033333
403    0.033333
410    0.033333
417    0.033333
419    0.033333
420    0.033333
430    0.033333
431    0.033333
466    0.033333
467    0.033333
478    0.033333
499    0.033333
500    0.033333
511    0.033333
512    0.033333
521    0.033333
534    0.033333
540    0.033333
550    0.033333
551    0.033333
Name: total m, dtype: float64