In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("sample_data.csv")
df.head()

,employee_id,name,department,salary,age,joining_date,city,performance_score,is_active
0,101,Aarav Sharma,Engineering,85000,28,2021-03-15,Delhi,4.5,True
1,102,Priya Mehta,Marketing,62000,32,2019-07-22,Mumbai,3.8,True
2,103,Rohan Verma,Engineering,92000,35,2018-01-10,Bangalore,4.7,True
3,104,Sneha Iyer,HR,54000,27,2022-05-30,Chennai,4.1,True
4,105,Kunal Joshi,Finance,71000,30,2020-11-18,Pune,3.5,False

# use of groupby

In [7]:
avg_df=df.groupby('department')['salary'].mean()

# find duplicates

In [10]:
df_dupliacte=df[df.duplicated('department')]
df_dupliacte

,employee_id,name,department,salary,age,joining_date,city,performance_score,is_active
2,103,Rohan Verma,Engineering,92000,35,2018-01-10,Bangalore,4.7,True
5,106,Ananya Singh,Engineering,88000,29,2021-08-05,Hyderabad,4.6,True
6,107,Vikram Nair,Marketing,67000,34,2018-09-14,Delhi,3.9,True
7,108,Divya Patel,Finance,74000,31,2019-04-25,Ahmedabad,4.2,True
8,109,Arjun Kapoor,HR,57000,26,2023-01-12,Mumbai,3.7,False
9,110,Meera Reddy,Engineering,95000,37,2017-06-08,Bangalore,4.9,True
11,112,Nisha Gupta,Marketing,60000,28,2022-10-01,Delhi,3.6,True
12,113,Rahul Bose,Data Science,98000,36,2019-12-17,Pune,4.4,False
13,114,Tanvi Sharma,Engineering,83000,27,2022-03-29,Chennai,4.3,True
14,115,Karan Malhotra,Finance,69000,29,2021-07-11,Mumbai,3.8,True
15,116,Pooja Tiwari,HR,52000,25,2023-06-15,Delhi,4.0,True
16,117,Aditya Kumar,Data Science,110000,38,2016-11-03,Bangalore,4.9,True
17,118,Riya Chopra,Marketing,63000,30,2020-08-19,Hyderabad,3.7,False
18,119,Manish Sinha,Engineering,89000,32,2019-05-07,Pune,4.5,True
19,120,Deepika Rao,Data Science,102000,34,2018-03-22,Mumbai,4.6,True